# Generated by Django 3.1.1 on 2020-10-04 20:06

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('myclubuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.myclubuser')),
                ('date_joined', models.DateTimeField()),
            ],
            bases=('events.myclubuser',),
        ),
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('events', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='venue',
            managers=[
                ('local_venues', django.db.models.manager.Manager()),
            ],
        ),
    ]
